name: Build MauiStarbucks

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndroid:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: List installed .NET info
      shell: pwsh
      run: dotnet --info

    - name: Restore nuget packages
      run: |
        cd src/MauiStarbucks
        dotnet restore MauiStarbucks.sln
   
    - name : Build Android App
      run: |
        cd src/MauiStarbucks
        dotnet publish -f:net6.0-android -c:Release
    
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts-android
        path: |
          src/MauiStarbucks\bin\Release\net6.0-android\publish\*.apk
    
    - name: Download APK
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-android
        path: |
          src\MauiStarbucks\bin\Release\net6.0-android\publish\*.apk

  #deployAppCenter:
  #  runs-on: ubuntu-latest
  #  steps:  
  #  - name: App Center Distribute
  #    uses: wzieba/AppCenter-Github-Action@v1.3.3
  #    with:
  #        appName: orgs/dotNET-MAUI/apps/MauiStarbucks
  #        token: ${{secrets.APP_CENTER_TOKEN}}
  #        group: Public
  #        file: src\MauiStarbucks\bin\Release\net6.0-android\publish\com.companyname.mauistarbucks-Signed.apk
  #        debug: false
      
